module MageSoap
  module ApiConstants
    VISIBILITY_BOTH = 4
    VISIBILITY_IN_CATALOG = 2
    VISIBILITY_IN_SEARCH = 3
    VISIBILITY_NOT_VISIBLE = 1

    STATUS_DISABLED = 2
    STATUS_ENABLED = 1
  end
end
